### ISSUE TITLE
Confusing example for "Remove unread private member"

### ISSUE THREAD

**Issue by davidferneding** [KristofferStrube/EditorConfigWizard#17]
In the example, `_lastWasTails` is unused, but in the fixed version, the code is refactored to use `_lastWasTails` and the now unused member `_lastWasHeads` is removed. The rule would not apply here, but while using the wizard, I had to stop for a moment to figure out why the previously used member was removed. I would suggest to change the fixed version to
```c#
class Coin
{
    private bool _lastWasHeads;
    private int _tosses;

    public void Flip()
    {
        toss = Random.Shared.Next(1)
        _lastWasHeads = toss == 1
        _tosses++
    }

    public bool headWon() => _lastWasHeads;
}
```

I'd be happy to open a pr to fix this if you consider this an issue as well.

![grafik](https://github.com/user-attachments/assets/eba5a4fb-45f1-4f1d-a77f-1a2f3e3e7752)

**Comment by KristofferStrube** [comment]
Hey @davidferneding,

Thanks for noticing. :) I have changed the sample now to be simpler and more correct.

![image](https://github.com/user-attachments/assets/6f3c8418-a2fb-43e3-8f21-4140a924d64c)
